"""Canonical permission codes — enforced on API, never only in UI."""

PERMISSIONS: dict[str, str] = {
    "system.manage": "Full system control",
    "club.manage": "Manage club settings",
    "users.manage": "Manage users and roles",
    "players.manage": "Create/update players",
    "players.view": "View player profiles",
    "teams.manage": "Manage teams and leadership",
    "teams.view": "View teams",
    "selection.manage": "Select Playing XI",
    "matches.manage": "Create/edit matches",
    "matches.view": "View matches",
    "scoring.manage": "Live ball-by-ball scoring",
    "training.manage": "Manage training sessions",
    "attendance.manage": "Manage attendance",
    "availability.manage": "View team availability",
    "discipline.issue_warning": "Issue warnings",
    "discipline.suspend": "Suspend players",
    "discipline.ban": "Ban players",
    "discipline.view_team": "View team disciplinary status",
    "discipline.view_sensitive": "View full disciplinary details",
    "notifications.send": "Send announcements/notifications",
    "sponsors.manage": "Manage sponsors",
    "sponsors.view_own": "View own sponsorship",
    "finance.manage": "Manage income/expenses",
    "finance.view": "View finance dashboard",
    "inventory.manage": "Manage equipment",
    "news.manage": "Publish news",
    "gallery.manage": "Manage gallery",
    "reports.view": "Generate reports",
    "audit.view": "View audit logs",
    "portal.player": "Access player portal",
}

ROLE_PERMISSION_MAP: dict[str, list[str]] = {
    "super_admin": list(PERMISSIONS.keys()),
    "club_admin": [
        "club.manage",
        "users.manage",
        "players.manage",
        "players.view",
        "teams.manage",
        "teams.view",
        "selection.manage",
        "matches.manage",
        "matches.view",
        "scoring.manage",
        "training.manage",
        "attendance.manage",
        "availability.manage",
        "discipline.issue_warning",
        "discipline.suspend",
        "discipline.ban",
        "discipline.view_team",
        "discipline.view_sensitive",
        "notifications.send",
        "sponsors.manage",
        "finance.manage",
        "finance.view",
        "inventory.manage",
        "news.manage",
        "gallery.manage",
        "reports.view",
        "audit.view",
    ],
    "team_manager": [
        "players.view",
        "teams.view",
        "selection.manage",
        "matches.view",
        "training.manage",
        "attendance.manage",
        "availability.manage",
        "discipline.issue_warning",
        "discipline.suspend",
        "discipline.view_team",
        "discipline.view_sensitive",
        "notifications.send",
        "reports.view",
    ],
    "captain": [
        "players.view",
        "teams.view",
        "selection.manage",
        "matches.view",
        "availability.manage",
        "discipline.issue_warning",
        "discipline.view_team",
        "notifications.send",
        "portal.player",
    ],
    "vice_captain": [
        "players.view",
        "teams.view",
        "matches.view",
        "availability.manage",
        "discipline.view_team",
        "portal.player",
    ],
    "coach": [
        "players.view",
        "teams.view",
        "selection.manage",
        "matches.view",
        "training.manage",
        "attendance.manage",
        "availability.manage",
        "discipline.view_team",
        "notifications.send",
    ],
    "scorer": [
        "matches.view",
        "scoring.manage",
        "players.view",
        "teams.view",
    ],
    "sponsor_manager": [
        "sponsors.manage",
        "finance.view",
        "reports.view",
    ],
    "sponsor": [
        "sponsors.view_own",
    ],
    "player": [
        "portal.player",
        "players.view",
        "teams.view",
        "matches.view",
    ],
    "viewer": [
        "matches.view",
        "teams.view",
    ],
}

ROLE_LABELS = {
    "super_admin": "Super Admin",
    "club_admin": "Club Admin",
    "team_manager": "Team Manager",
    "captain": "Captain",
    "vice_captain": "Vice Captain",
    "coach": "Coach",
    "scorer": "Scorer",
    "sponsor_manager": "Sponsor Manager",
    "sponsor": "Sponsor",
    "player": "Player",
    "viewer": "Viewer",
}
